#! /bin/bash

# Send the current crontab to stdout, filter out lines containing
# "#DILUCID", append the line to run dilucid, and pipe the result into
# crontab again

crontab -l | grep --invert-match \#DILUCID | cat - dilucid-line.cron | crontab
